"""add routing/outcome telemetry tables (ADR-0003)

Revision ID: 5e7a9c1d3f20
Revises: 8a4f2c9e1b3d
Create Date: 2026-09-27 19:04:06.394254
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5e7a9c1d3f20"
down_revision: str | Sequence[str] | None = "8a4f2c9e1b3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_export_batches',
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('feedback_count', sa.Integer(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('telemetry_feedback',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('original_value_hash', sa.String(length=64), nullable=True),
    sa.Column('sanitized_corrected_value', sa.Text(), nullable=True),
    sa.Column('correction_distance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.Column('export_batch_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_telemetry_feedback_export_batch_id'), 'telemetry_feedback', ['export_batch_id'], unique=False)
    op.create_index(op.f('ix_telemetry_feedback_run_id'), 'telemetry_feedback', ['run_id'], unique=False)
    op.create_table('telemetry_model_attempts',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_micro', sa.BigInteger(), nullable=True),
    sa.Column('cost_measurement', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_telemetry_model_attempts_run_id'), 'telemetry_model_attempts', ['run_id'], unique=False)
    op.create_table('telemetry_ops_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.String(length=120), nullable=True),
    sa.Column('policy_version', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_telemetry_ops_events_created_at'), 'telemetry_ops_events', ['created_at'], unique=False)
    op.create_table('telemetry_outcome_signals',
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.String(length=40), nullable=False),
    sa.Column('strength', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.Column('export_batch_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_telemetry_outcome_signals_export_batch_id'), 'telemetry_outcome_signals', ['export_batch_id'], unique=False)
    op.create_index(op.f('ix_telemetry_outcome_signals_run_id'), 'telemetry_outcome_signals', ['run_id'], unique=False)
    op.create_table('telemetry_router_decisions',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version', sa.String(length=120), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=80), nullable=False),
    sa.Column('algorithm', sa.String(length=40), nullable=False),
    sa.Column('selected_model', sa.String(length=120), nullable=False),
    sa.Column('selected_provider', sa.String(length=80), nullable=False),
    sa.Column('selection_probability', sa.Float(), nullable=False),
    sa.Column('action_probabilities_json', sa.Text(), nullable=False),
    sa.Column('eligible_models_json', sa.Text(), nullable=False),
    sa.Column('exploration', sa.Boolean(), nullable=False),
    sa.Column('shadow', sa.Boolean(), nullable=False),
    sa.Column('agreed_with_live', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_telemetry_router_decisions_run_id'), 'telemetry_router_decisions', ['run_id'], unique=False)
    op.create_table('telemetry_run_outcomes',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('first_shot_success', sa.Boolean(), nullable=False),
    sa.Column('structured_output_valid', sa.Boolean(), nullable=True),
    sa.Column('tool_success', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('user_retry_signal', sa.Boolean(), nullable=False),
    sa.Column('user_abandon_signal', sa.Boolean(), nullable=False),
    sa.Column('user_accept_signal', sa.Boolean(), nullable=False),
    sa.Column('user_correction_signal', sa.Boolean(), nullable=False),
    sa.Column('correction_distance', sa.Float(), nullable=True),
    sa.Column('final_latency_ms', sa.Integer(), nullable=False),
    sa.Column('final_cost_micro', sa.BigInteger(), nullable=True),
    sa.Column('cost_measurement', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_telemetry_run_outcomes_finalized_at'), 'telemetry_run_outcomes', ['finalized_at'], unique=False)
    op.create_table('telemetry_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('session_id_hash', sa.String(length=64), nullable=True),
    sa.Column('anonymous_actor_id', sa.String(length=64), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_domain', sa.String(length=40), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('harness_version', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('policy_version', sa.String(length=120), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=80), nullable=False),
    sa.Column('telemetry_schema_version', sa.String(length=40), nullable=False),
    sa.Column('app_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=False),
    sa.Column('eligible_models_json', sa.Text(), nullable=False),
    sa.Column('eligibility_rejections_json', sa.Text(), nullable=False),
    sa.Column('live_fallback_reason', sa.String(length=120), nullable=True),
    sa.Column('shadow_error', sa.String(length=120), nullable=True),
    sa.Column('export_batch_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_telemetry_runs_anonymous_actor_id'), 'telemetry_runs', ['anonymous_actor_id'], unique=False)
    op.create_index(op.f('ix_telemetry_runs_completed_at'), 'telemetry_runs', ['completed_at'], unique=False)
    op.create_index(op.f('ix_telemetry_runs_export_batch_id'), 'telemetry_runs', ['export_batch_id'], unique=False)
    op.create_index(op.f('ix_telemetry_runs_request_fingerprint'), 'telemetry_runs', ['request_fingerprint'], unique=False)
    op.create_table('telemetry_tool_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('schema_valid', sa.Boolean(), nullable=False),
    sa.Column('execution_success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_telemetry_tool_events_run_id'), 'telemetry_tool_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_tool_events_run_id'), table_name='telemetry_tool_events')
    op.drop_table('telemetry_tool_events')
    op.drop_index(op.f('ix_telemetry_runs_request_fingerprint'), table_name='telemetry_runs')
    op.drop_index(op.f('ix_telemetry_runs_export_batch_id'), table_name='telemetry_runs')
    op.drop_index(op.f('ix_telemetry_runs_completed_at'), table_name='telemetry_runs')
    op.drop_index(op.f('ix_telemetry_runs_anonymous_actor_id'), table_name='telemetry_runs')
    op.drop_table('telemetry_runs')
    op.drop_index(op.f('ix_telemetry_run_outcomes_finalized_at'), table_name='telemetry_run_outcomes')
    op.drop_table('telemetry_run_outcomes')
    op.drop_index(op.f('ix_telemetry_router_decisions_run_id'), table_name='telemetry_router_decisions')
    op.drop_table('telemetry_router_decisions')
    op.drop_index(op.f('ix_telemetry_outcome_signals_run_id'), table_name='telemetry_outcome_signals')
    op.drop_index(op.f('ix_telemetry_outcome_signals_export_batch_id'), table_name='telemetry_outcome_signals')
    op.drop_table('telemetry_outcome_signals')
    op.drop_index(op.f('ix_telemetry_ops_events_created_at'), table_name='telemetry_ops_events')
    op.drop_table('telemetry_ops_events')
    op.drop_index(op.f('ix_telemetry_model_attempts_run_id'), table_name='telemetry_model_attempts')
    op.drop_table('telemetry_model_attempts')
    op.drop_index(op.f('ix_telemetry_feedback_run_id'), table_name='telemetry_feedback')
    op.drop_index(op.f('ix_telemetry_feedback_export_batch_id'), table_name='telemetry_feedback')
    op.drop_table('telemetry_feedback')
    op.drop_table('telemetry_export_batches')
    # ### end Alembic commands ###

