"""initial daily agent schema

Revision ID: 92174af1e5c5
Revises: 
Create Date: 2026-09-10 20:06:31.171554
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '92174af1e5c5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('source_event_id', sa.String(length=160), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'source_event_id')
    )
    op.create_table('platform_budgets',
    sa.Column('window_key', sa.String(length=40), nullable=False),
    sa.Column('spend_limit_micro', sa.Integer(), nullable=False),
    sa.Column('reserved_micro', sa.Integer(), nullable=False),
    sa.Column('settled_micro', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('window_key')
    )
    op.create_table('billing_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_event_id', sa.String(length=160), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id')
    )
    op.create_index(op.f('ix_billing_events_account_id'), 'billing_events', ['account_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=20), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('usage_windows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('window_key', sa.String(length=40), nullable=False),
    sa.Column('everyday_limit', sa.Integer(), nullable=False),
    sa.Column('everyday_used', sa.Integer(), nullable=False),
    sa.Column('spend_limit_micro', sa.Integer(), nullable=False),
    sa.Column('reserved_micro', sa.Integer(), nullable=False),
    sa.Column('settled_micro', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'window_key')
    )
    op.create_index(op.f('ix_usage_windows_account_id'), 'usage_windows', ['account_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_table('budget_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('logical_request_id', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('usage_window_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('reserved_micro', sa.Integer(), nullable=False),
    sa.Column('actual_micro', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usage_window_id'], ['usage_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_request_id', 'stage')
    )
    op.create_index(op.f('ix_budget_reservations_account_id'), 'budget_reservations', ['account_id'], unique=False)
    op.create_index(op.f('ix_budget_reservations_logical_request_id'), 'budget_reservations', ['logical_request_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_account_id'), 'notes', ['account_id'], unique=False)
    op.create_index(op.f('ix_notes_owner_user_id'), 'notes', ['owner_user_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('due_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_reminders_account_id'), 'reminders', ['account_id'], unique=False)
    op.create_index(op.f('ix_reminders_owner_user_id'), 'reminders', ['owner_user_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('logical_request_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_request_id')
    )
    op.create_index(op.f('ix_runs_account_id'), 'runs', ['account_id'], unique=False)
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_tasks_account_id'), 'tasks', ['account_id'], unique=False)
    op.create_index(op.f('ix_tasks_owner_user_id'), 'tasks', ['owner_user_id'], unique=False)
    op.create_table('cost_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=False),
    sa.Column('cost_micro', sa.Integer(), nullable=True),
    sa.Column('measurement', sa.String(length=20), nullable=False),
    sa.Column('rate_version', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['budget_reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_ledger_reservation_id'), 'cost_ledger', ['reservation_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('logical_key', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_key')
    )
    op.create_index(op.f('ix_outbox_events_run_id'), 'outbox_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_run_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_cost_ledger_reservation_id'), table_name='cost_ledger')
    op.drop_table('cost_ledger')
    op.drop_index(op.f('ix_tasks_owner_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_account_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_runs_user_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_account_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_reminders_owner_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_account_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_notes_owner_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_account_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_budget_reservations_logical_request_id'), table_name='budget_reservations')
    op.drop_index(op.f('ix_budget_reservations_account_id'), table_name='budget_reservations')
    op.drop_table('budget_reservations')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_windows_account_id'), table_name='usage_windows')
    op.drop_table('usage_windows')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_billing_events_account_id'), table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_table('platform_budgets')
    op.drop_table('inbox_events')
    op.drop_table('accounts')
    # ### end Alembic commands ###

