import 'package:flutter/material.dart';

import 'karmi_tier.dart';

part 'tier_tokens.g.dart';

/// Semantic colour tokens for one tier × mode (the Flutter equivalent of the
/// plan's CSS custom properties; docs/design/implementation_plan.md §1.2).
///
/// Values are generated by `mobile/tool/derive_theme_tokens.py` from
/// docs/design/karmi_tier_color_palettes.md into `tier_tokens.g.dart`; the
/// contrast audit for all 8 combinations lives in
/// docs/design/karmi_theme_tokens.json and test/theme/karmi_colors_test.dart.
///
/// Roles:
/// - [primary]: the tier's Active/Primary Accent. Fills only (CTAs, progress,
///   user bubble) with [primaryForeground] text; never text on surfaces.
/// - [primaryText]: accent-family ink that is ≥4.5:1 on background/card/muted
///   (links, icons, spinners). In light mode it is the Primary Base (or a
///   darkened accent for Parth); in dark mode the accent itself.
/// - [accent]: the tier's second colour (Primary Base; Parth's Iridescent Purple).
/// - [header]: the palette's structural "Primary Base" for solid headers.
/// - `glass*`: frosted-panel tint (alpha at the §5.1 legibility floor), border
///   and top-edge highlight.
@immutable
class KarmiColors extends ThemeExtension<KarmiColors> {
  const KarmiColors({
    required this.background,
    required this.foreground,
    required this.card,
    required this.cardForeground,
    required this.primary,
    required this.primaryForeground,
    required this.primaryText,
    required this.secondary,
    required this.secondaryForeground,
    required this.accent,
    required this.accentForeground,
    required this.muted,
    required this.mutedForeground,
    required this.border,
    required this.borderSubtle,
    required this.ring,
    required this.destructive,
    required this.destructiveForeground,
    required this.success,
    required this.warning,
    required this.header,
    required this.glassBase,
    required this.glassBorder,
    required this.glassHighlight,
  });

  final Color background;
  final Color foreground;
  final Color card;
  final Color cardForeground;
  final Color primary;
  final Color primaryForeground;
  final Color primaryText;
  final Color secondary;
  final Color secondaryForeground;
  final Color accent;
  final Color accentForeground;
  final Color muted;
  final Color mutedForeground;
  final Color border;
  final Color borderSubtle;
  final Color ring;
  final Color destructive;
  final Color destructiveForeground;
  final Color success;
  final Color warning;
  final Color header;
  final Color glassBase;
  final Color glassBorder;
  final Color glassHighlight;

  /// Constant-time lookup of the generated tokens.
  static KarmiColors forTier(KarmiTier tier, Brightness brightness) =>
      _tierTokens[tier]![brightness]!;

  static KarmiColors of(BuildContext context) =>
      Theme.of(context).extension<KarmiColors>()!;

  @override
  KarmiColors copyWith({
    Color? background,
    Color? foreground,
    Color? card,
    Color? cardForeground,
    Color? primary,
    Color? primaryForeground,
    Color? primaryText,
    Color? secondary,
    Color? secondaryForeground,
    Color? accent,
    Color? accentForeground,
    Color? muted,
    Color? mutedForeground,
    Color? border,
    Color? borderSubtle,
    Color? ring,
    Color? destructive,
    Color? destructiveForeground,
    Color? success,
    Color? warning,
    Color? header,
    Color? glassBase,
    Color? glassBorder,
    Color? glassHighlight,
  }) {
    return KarmiColors(
      background: background ?? this.background,
      foreground: foreground ?? this.foreground,
      card: card ?? this.card,
      cardForeground: cardForeground ?? this.cardForeground,
      primary: primary ?? this.primary,
      primaryForeground: primaryForeground ?? this.primaryForeground,
      primaryText: primaryText ?? this.primaryText,
      secondary: secondary ?? this.secondary,
      secondaryForeground: secondaryForeground ?? this.secondaryForeground,
      accent: accent ?? this.accent,
      accentForeground: accentForeground ?? this.accentForeground,
      muted: muted ?? this.muted,
      mutedForeground: mutedForeground ?? this.mutedForeground,
      border: border ?? this.border,
      borderSubtle: borderSubtle ?? this.borderSubtle,
      ring: ring ?? this.ring,
      destructive: destructive ?? this.destructive,
      destructiveForeground:
          destructiveForeground ?? this.destructiveForeground,
      success: success ?? this.success,
      warning: warning ?? this.warning,
      header: header ?? this.header,
      glassBase: glassBase ?? this.glassBase,
      glassBorder: glassBorder ?? this.glassBorder,
      glassHighlight: glassHighlight ?? this.glassHighlight,
    );
  }

  @override
  KarmiColors lerp(ThemeExtension<KarmiColors>? other, double t) {
    if (other is! KarmiColors) return this;
    Color l(Color a, Color b) => Color.lerp(a, b, t)!;
    return KarmiColors(
      background: l(background, other.background),
      foreground: l(foreground, other.foreground),
      card: l(card, other.card),
      cardForeground: l(cardForeground, other.cardForeground),
      primary: l(primary, other.primary),
      primaryForeground: l(primaryForeground, other.primaryForeground),
      primaryText: l(primaryText, other.primaryText),
      secondary: l(secondary, other.secondary),
      secondaryForeground: l(secondaryForeground, other.secondaryForeground),
      accent: l(accent, other.accent),
      accentForeground: l(accentForeground, other.accentForeground),
      muted: l(muted, other.muted),
      mutedForeground: l(mutedForeground, other.mutedForeground),
      border: l(border, other.border),
      borderSubtle: l(borderSubtle, other.borderSubtle),
      ring: l(ring, other.ring),
      destructive: l(destructive, other.destructive),
      destructiveForeground: l(
        destructiveForeground,
        other.destructiveForeground,
      ),
      success: l(success, other.success),
      warning: l(warning, other.warning),
      header: l(header, other.header),
      glassBase: l(glassBase, other.glassBase),
      glassBorder: l(glassBorder, other.glassBorder),
      glassHighlight: l(glassHighlight, other.glassHighlight),
    );
  }
}
